/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package mocktest;

import static org.mockito.Mockito.*;
import static org.mockito.Mockito.verify;

import java.util.List;


public class Library {
    public boolean someLibraryMethod() {
    	List mocked = mock(List.class);
        return true;
    }
}
